### PR TITLE
refactor: adjust transaction details UI

### PR DESCRIPTION
**Pull request by goga-m**
Closes https://app.clickup.com/t/86dtzx84b

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — CHANGES_REQUESTED** [review]
@goga-m  - Some general remarks on the modal before I go into detail on each transaction type

---

**External Link Icon**
The external link icon within the modal shouldn't have a background colour.
Design
image

Imp
image

---

**Success Icon**
Success Icon should be 20x20. Currently 16x16 
image

---
**Success Text**
Success text should be `#307845` and semi bold. 
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
**Multipayment**
Here's some issues I noticed on the Multipayment modal:

**Multiple (N)**
The Multiple (N) text isn't currently styled correctly. 
- The "Multple" text should be semi bold
- The "(N)" should be semi bold and  `#637282`)

---
**Padding**
The space either side of the divider line is currently too large. Should be 8px each side

Design
image

Imp
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
**Vote Modal**

Here's some issues on the Vote Modals (these issues exist on Vote/Unvote/Vote Swap):

**Alignment**
The details within the modal should all be aligned. Currently the Vote details are not aligned
Design
image

---
**Divider Lines**
The Transaction Type section currently contains a divider line between Category and Delegate. This should be removed

Design
image

Imp
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Delegate Registration & Resignation

- The delegate name should be semi bold. 

Design
image

Implementation
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
**Multisignature**

- The Copy icons within the Participants address list should be `#5CA4EC`
image

Currently it's black.

**Review by samharperpittam — APPROVED** [review]

**Review by patricio0312rev — APPROVED** [review]

**Pull request merged**
