### PR TITLE
refactor: select recipient modal  - component

### PR DESCRIPTION
**Pull request by patricio0312rev**
# [[send] adjust recipient selection modal](https://app.clickup.com/t/86du9tcgu) - component

## Summary

- `Table` and `TableCell` components have been refactored implementing new styles.
- Both the icons and translations have been updated.
- The search input has been refactored.
- New `RecipientItemMobile` component.
- Dark mode styles have also been refactored.

## Screenshots

image

image

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Comment by patricio0312rev** [comment]
> Note: I noticed there is now a space between the border of the table rows and the general border of the table. There is already a ticket to address the table overview, it should be fixed there, since doing it here would require a refactor in the entire table component and don't want to make the PR that big 🤔 

image

**Comment by patricio0312rev** [comment]
Tests in: https://github.com/ArdentHQ/arkvault/pull/600

**Review by samharperpittam — CHANGES_REQUESTED** [review]
From 640 down, using a long wallet name causes the content to get pushed out of view. May need to truncate wallet name if it's too long. 

image

**Comment by patricio0312rev** [comment]
@samharperpittam issue should be fixed now ✅

**Review by samharperpittam — APPROVED** [review]

**Pull request merged**
